# Working Analysis For All of the Single Phase Projects

## Imports and Setup

In [1]:
from pathlib import Path

import pandas as pd

pd.options.display.float_format = '{:,.4f}'.format
pd.options.display.max_columns = 100
pd.options.display.max_rows = 100

In [2]:
library_path = Path("library").resolve()
project_order = [
    "Revolution Wind",
    "CVOW C",
    "Sunrise Wind",
    "Kitty Hawk North",
    "Marwin",
    "Momentum Wind",
    "Future Development",
    "US Wind",
    "Park City",
    "Commonwealth",
    "New England",
    "Empire Wind 1",
    "Empire Wind 2",
    "Empire Wind",
    "Atlantic Shores South 1",
    "Atlantic Shores South 2",
    "Atlantic Shores South",
    "Mayflower Wind 1",
    "Mayflower Wind 2",
    "Mayflower Wind",
    "Ocean Wind 1",
]

In [3]:
outputs = pd.concat(
    [
        pd.read_csv(library_path / "results" / f"{project.replace(' ', '_')}_metrics.csv", index_col="Metrics")
        for project in project_order
    ],
    axis=1
)[project_order]
inputs = pd.concat(
    [
        pd.read_csv(library_path / "results" / f"{project.replace(' ', '_')}_inputs.csv", index_col="Inputs")
        for project in project_order
    ],
    axis=1
)[project_order]

In [4]:
outputs.to_csv(library_path / "results" / "outputs.csv")
inputs.to_csv(library_path / "results" / "inputs.csv")

In [5]:
outputs

,Revolution Wind,CVOW C,Sunrise Wind,Kitty Hawk North,Marwin,Momentum Wind,Future Development,US Wind,Park City,Commonwealth,New England,Empire Wind 1,Empire Wind 2,Empire Wind,Atlantic Shores South 1,Atlantic Shores South 2,Atlantic Shores South,Mayflower Wind 1,Mayflower Wind 2,Mayflower Wind,Ocean Wind 1
Metrics,,,,,,,,,,,,,,,,,,,,,
# Turbines,79.0000,176.0000,102.0000,69.0000,21.0000,55.0000,38.0000,114.0000,50.0000,78.0000,128.0000,54.0000,85.0000,139.0000,136.0000,64.0000,200.0000,80.0000,67.0000,147.0000,98.0000
Turbine Rating (MW),11.0000,15.0000,11.0000,15.0000,15.0000,15.0000,15.0000,15.0000,16.0000,16.0000,16.0000,15.0000,15.0000,15.0000,15.0000,15.0000,15.0000,15.0000,15.0000,15.0000,12.0000
Project Capacity (MW),869.0000,"2,640.0000","1,122.0000","1,035.0000",315.0000,825.0000,570.0000,"1,710.0000",800.0000,"1,248.0000","2,048.0000",810.0000,"1,275.0000","2,085.0000","2,040.0000",960.0000,"3,000.0000","1,200.0000","1,005.0000","2,205.0000","1,176.0000"
# OSS,2.0000,3.0000,1.0000,1.0000,1.0000,2.0000,1.0000,4.0000,1.0000,1.0000,2.0000,1.0000,1.0000,2.0000,2.0000,1.0000,3.0000,1.0000,1.0000,2.0000,3.0000
Total Export Cable Length (km),229.0341,594.2578,394.0950,294.1048,58.0250,116.0501,116.0501,232.1002,330.1533,440.2044,770.3577,225.1047,315.1745,540.2792,250.1218,354.0731,604.1949,276.1518,312.1012,588.2530,237.0791
Total Array Cable Length (km),186.9965,354.9487,296.3930,251.1396,34.9900,100.7003,71.9402,200.5584,142.0922,201.3542,343.4464,144.6603,165.6436,310.3039,233.1351,101.4056,346.6873,227.1130,159.8160,386.9290,208.0796
FCR (%),0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582
Offtake Price ($/MWh),99.0300,89.0600,83.3000,89.0600,131.9000,71.6000,86.7000,86.7000,79.8000,72.0000,75.0700,83.3000,107.5000,97.9900,58.8000,58.8000,58.8000,58.4000,77.0000,64.5600,116.8000
CapEx ($),"2,994,396,587.8047","7,813,031,773.1017","3,751,881,179.4308","3,591,735,599.6405","1,106,039,758.1098","2,577,120,805.9140","1,906,470,115.5788","5,192,854,896.0160","2,782,692,391.9032","4,145,146,082.0531","6,761,130,068.5989","2,566,363,303.0008","3,953,159,331.5253","6,319,721,993.7719","6,091,033,074.0887","3,344,872,843.8961","9,324,020,799.4184","4,324,859,019.6342","3,498,635,149.3500","7,452,923,652.6752","3,778,849,941.3333"
CapEx per kW ($/kW),"3,445.7958","2,959.4817","3,343.9226","3,470.2759","3,511.2373","3,123.7828","3,344.6844","3,036.7572","3,478.3655","3,321.4312","3,301.3330","3,168.3498","3,100.5171","3,031.0417","2,985.8005","3,484.2425","3,108.0069","3,604.0492","3,481.2290","3,380.0107","3,213.3078"
System CapEx for Export Cables ($),"389,357,970.0000","505,119,096.0000","197,047,520.0000","499,978,143.0000","98,642,568.0000","197,285,136.0000","197,285,136.0000","394,570,272.0000","280,630,305.0000","374,173,740.0000","654,804,045.0000","191,338,995.0000","267,898,325.0000","459,237,320.0000","425,207,060.0000","601,924,236.0000","1,027,131,296.0000","469,458,009.0000","156,050,590.0000","625,508,599.0000","403,034,547.0025"
Installation CapEx for Export Cables ($),"19,491,941.8499","29,822,186.6380","11,797,577.5250","29,851,871.1178","12,246,417.0200","15,865,772.1961","15,865,772.1961","22,794,893.5073","31,124,165.8543","35,679,524.7253","53,192,245.1741","10,387,948.7549","19,940,423.6525","30,328,372.4074","27,549,848.0453","32,590,114.4232","60,139,962.4686","29,094,918.3041","13,722,100.9881","42,817,019.2922","25,754,444.8273"
CapEx Without Export Cables ($),"2,585,546,675.9548","7,278,090,490.4637","3,543,036,081.9058","3,061,905,585.5227","995,150,773.0898","2,363,969,897.7179","1,693,319,207.3827","4,775,489,730.5087","2,470,937,921.0489","3,735,292,817.3278","6,053,133,778.4248","2,364,636,359.2459","3,665,320,582.8728","5,830,156,301.3645","5,638,276,166.0434","2,710,358,493.4729","8,236,749,540.9499","3,826,306,092.3301","3,328,862,458.3619","6,784,598,034.3830","3,350,060,949.5035"
OpEx ($),"1,318,220,249.8385","1,780,269,423.3567","1,537,556,762.7670","1,224,412,482.1537","911,686,782.8531","1,454,438,390.7545","1,254,221,590.4897","1,729,583,938.2979","1,123,635,119.3171","1,430,446,937.0962","1,691,011,577.2691","1,121,036,625.9072","1,310,301,101.4842","1,684,569,763.7137","1,786,574,043.2814","1,254,561,801.4801","1,961,905,108.9126","1,855,284,222.1905","1,576,624,345.4794","2,074,591,029.9835","1,776,457,716.3631"
OpEx per kW ($/kW),"1,516.9393",674.3445,"1,370.3714","1,183.0072","2,894.2438","1,762.9556","2,200.3888","1,011.4526","1,404.5439","1,146.1915",825.6892,"1,383.9958","1,027.6871",807.9471,875.7716,"1,306.8352",653.9684,"1,546.0702","1,568.7804",940.8576,"1,510.5933"
Annual OpEx per kW ($/kW),72.2352,32.1116,65.2558,56.3337,137.8211,83.9503,104.7804,48.1644,66.8830,54.5805,39.3185,65.9046,48.9375,38.4737,41.7034,62.2302,31.1414,73.6224,74.7038,44.8027,71.9330
Energy Availability (%),0.9489,0.9498,0.9434,0.9416,0.9053,0.9074,0.9100,0.9272,0.9465,0.9440,0.9420,0.9587,0.9539,0.9505,0.9362,0.9452,0.9508,0.9187,0.9155,0.9384,0.9191
Gross Capacity Factor (%),0.5271,0.4259,0.5207,0.4588,0.4867,0.3547,0.3611,0.3485,0.5242,0.5101,0.5163,0.3812,0.4098,0.3574,0.4012,0.4103,0.3935,0.5237,0.5276,0.5190,0.4741
Net Capacity Factor Without Unmodeled Losses (%),0.5001,0.4045,0.4912,0.4319,0.4404,0.3218,0.3285,0.3231,0.4961,0.4815,0.4863,0.3653,0.3909,0.3396,0.3756,0.3876,0.3741,0.4811,0.4832,0.4870,0.4358
Annual Losses (MWh),"606,843.7286","1,481,028.2292","802,540.0395","660,500.2949","262,140.2679","494,586.4083","342,957.5350","902,719.6691","564,925.4334","871,418.7336","1,464,088.7488","383,786.8203","670,233.8156","978,617.6416","1,176,141.0010","537,005.1825","1,544,518.5941","998,819.9511","856,329.2389","1,621,007.9121","883,171.3168"
AEP (MWh),"3,408,581.8558","8,376,751.9051","4,319,749.7068","3,502,249.0062","1,081,860.3672","2,070,740.9914","1,461,364.4405","4,321,626.9087","3,111,629.9734","4,709,884.8117","7,804,980.6550","2,323,232.1238","3,910,753.4915","5,554,306.1739","5,999,907.9813","2,916,448.9473","8,804,496.2149","4,510,672.5932","3,792,124.1741","8,411,179.2760","4,004,364.8864"
AEP per kW (MWh/kW),3.9224,3.1730,3.8500,3.3838,3.4345,2.5100,2.5638,2.5273,3.8895,3.7739,3.8110,2.8682,3.0673,2.6639,2.9411,3.0380,2.9348,3.7589,3.7733,3.8146,3.4051
Net Capacity Factor With All Losses (%),0.4474,0.3619,0.4392,0.3860,0.3918,0.2863,0.2924,0.2883,0.4437,0.4305,0.4347,0.3272,0.3499,0.3039,0.3355,0.3465,0.3348,0.4288,0.4304,0.4351,0.3884
LCOE ($/MWh),69.5440,64.4036,67.4985,76.3351,99.6295,105.8787,116.7959,88.9909,69.2432,65.6840,60.7333,87.2685,74.7859,80.6627,73.2633,87.2337,72.2451,75.3887,73.4939,63.3146,76.0476
IRR (%),0.0056,0.0049,0.0042,0.0036,0.0055,-0.0014,-0.0006,0.0021,0.0036,0.0031,0.0040,0.0019,0.0054,0.0038,0.0004,-0.0012,0.0006,0.0000,0.0028,0.0024,0.0065
NPV ($),"-1,352,529,811.1067","-3,663,664,043.2028","-1,746,744,672.3226","-1,686,875,521.7199","-508,092,953.9161","-1,325,301,819.2470","-959,081,091.6766","-2,537,913,982.6514","-1,310,484,619.7826","-1,978,967,755.5803","-3,166,441,736.3750","-1,278,599,849.4530","-1,842,615,069.2810","-3,035,950,528.1264","-3,070,063,757.8768","-1,681,034,999.0079","-4,636,162,323.1086","-2,135,621,433.9181","-1,677,813,869.4970","-3,561,844,483.0489","-1,673,215,527.8771"

In [6]:
inputs

,Revolution Wind,CVOW C,Sunrise Wind,Kitty Hawk North,Marwin,Momentum Wind,Future Development,US Wind,Park City,Commonwealth,New England,Empire Wind 1,Empire Wind 2,Empire Wind,Atlantic Shores South 1,Atlantic Shores South 2,Atlantic Shores South,Mayflower Wind 1,Mayflower Wind 2,Mayflower Wind,Ocean Wind 1
Inputs,,,,,,,,,,,,,,,,,,,,,
FCR,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582,0.0582
Offtake price ($/MWh),99.03,89.06,83.3,89.06,131.9,71.6,86.7,86.7,79.8,72,75.07,83.3,107.5,97.99,58.8,58.8,58.8,58.4,77,64.56,116.8
Lease Area Price ($),1903181,1971276,1903181,10592835,10553535,10553535,10553535,10553535,182336,182336,182336,48611290,48611290,48611290,1205011,1205011,1205011,154525000,154525000,154525000,1054690
Discount rate (%),0.025,0.025,0.025,0.025,0.025,0.025,0.025,0.025,0.025,0.025,0.025,0.025,0.025,0.025,0.025,0.025,0.025,0.025,0.025,0.025,0.025
# Turbines,79,176,102,69,21,55,38,114,50,78,128,54,85,139,136,64,200,80,67,147,98
Turbine Rating (MW),11,15,11,15,15,15,15,15,16,16,16,15,15,15,15,15,15,15,15,15,12
Project Capacity (MW),869,2640,1122,1035,315,825,570,1710,800,1248,2048,810,1275,2085,2040,960,3000,1200,1005,2205,1176
# OSS,2,3,1,1,1,2,1,4,1,1,2,1,1,2,2,1,3,1,1,2,3
Substructure type,??,??,??,??,??,??,??,??,??,??,??,??,??,??,??,??,??,??,??,??,??
Row spacing (rotor diameters),not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts
Turbine spacing (rotor diameters),not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts,not used for custom layouts
Depth (m),34.7,28.64,47.52,34.93,25.04,25.04,25.04,25.04,51.1,51.1,51.1,34.9,34.9,34.9,24.36,24.36,24.36,50.59,50.59,50.59,26.381765177291
Mean wind speed (m/s),8.996010967057243,8.168117143172747,8.996010967057243,8.371018229890675,8.587894570207704,7.261211463442823,7.261211463442823,7.261211463442823,9.15166971905148,8.996010967057243,9.15166971905148,7.547582618743443,8.176109289572958,7.547582618743443,7.996682151675415,7.996682151675415,7.996682151675415,9.15166971905148,9.21673306772638,9.15166971905148,8.586498120787025
Distance to landfall (km),74.31,58,169,89,41,41,41,41,93,93,93,74,54,74,31,99,31,88,154,88,36
Distance to port (km),82,108,103,141,252,252,252,252,100,100,100,75,75,75,147,147,147,208,208,208,214
Interconnection distance (km),2,8,28,9,17,17,17,17,17,17,17,1,9,1,19,19,19,4,2,4,7
# of POIs,??,??,??,??,??,??,??,??,??,??,??,??,??,??,??,??,??,??,??,??,??
Export cable type,['XLPE_1900mm_275kV'],['XLPE_1000m_220kV'],['HVDC_2000mm_320kV'],['XLPE_1900mm_275kV'],['XLPE_1900mm_275kV'],['XLPE_1900mm_275kV'],['XLPE_1900mm_275kV'],['XLPE_1900mm_275kV'],['XLPE_1000m_220kV'],['XLPE_1000m_220kV'],['XLPE_1000m_220kV'],['XLPE_1000m_220kV'],['XLPE_1000m_220kV'],['XLPE_1000m_220kV'],['XLPE_1900mm_275kV'],['XLPE_1900mm_275kV'],['XLPE_1900mm_275kV'],['XLPE_1900mm_275kV'],['HVDC_2000mm_320kV'],['XLPE_1900mm_275kV'],['XLPE_1900mm_275kV']
Array cable type,"['XLPE_185mm_66kV', 'XLPE_630mm_66kV']","['XLPE_185mm_66kV', 'XLPE_630mm_66kV']","['XLPE_185mm_66kV', 'XLPE_500mm_132kV', 'XLPE_...","['XLPE_185mm_66kV', 'XLPE_630mm_66kV']","['XLPE_185mm_66kV', 'XLPE_630mm_66kV']","['XLPE_185mm_66kV', 'XLPE_630mm_66kV']","['XLPE_185mm_66kV', 'XLPE_630mm_66kV']","['XLPE_185mm_66kV', 'XLPE_630mm_66kV']","['XLPE_185mm_66kV', 'XLPE_500mm_132kV', 'XLPE_...","['XLPE_185mm_66kV', 'XLPE_500mm_132kV', 'XLPE_...","['XLPE_185mm_66kV', 'XLPE_500mm_132kV', 'XLPE_...","['XLPE_185mm_66kV', 'XLPE_630mm_66kV']","['XLPE_185mm_66kV', 'XLPE_630mm_66kV']","['XLPE_185mm_66kV', 'XLPE_630mm_66kV']","['XLPE_185mm_66kV', 'XLPE_500mm_132kV', 'XLPE_...","['XLPE_185mm_66kV', 'XLPE_500mm_132kV', 'XLPE_...","['XLPE_185mm_66kV', 'XLPE_500mm_132kV', 'XLPE_...","['XLPE_185mm_66kV', 'XLPE_630mm_66kV']","['XLPE_185mm_66kV', 'XLPE_630mm_66kV']","['XLPE_185mm_66kV', 'XLPE_630mm_66kV']","['XLPE_185mm_66kV', 'XLPE_500mm_132kV', 'XLPE_..."